version: '2'
services:
      
  grafana:
    container_name: grafana
    image: grafana/grafana:4.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana-data:/var/lib/grafana
      - ./grafana-plugins:/var/lib/grafana/plugins
    env_file:
      - .grafana.env
    ports:
      - "3000:3000"






     